[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"

[env]
PORT = "5000"
NODE_ENV = "production"